// DADOS COMPLETOS CONVERTIDOS DO SEU JSON
const riskData = [
{
    id: "I-1",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Exposição à Ruído contínuo",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Protetor auricular",
    controls: "Manutenção preventiva de equipamentos, rodízio de funcionários",
    legislation: "NR-15"
},
{
    id: "I-2", 
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Exposição à Vibração de Corpo Inteiro (VCI)",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Calçado de segurança com amortecimento",
    controls: "Limitação do tempo de exposição, pausas programadas",
    legislation: "NR-15"
},
{
    id: "I-3",
    area: "Manutenção Mecânica", 
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Exposição à Calor (Sobrecarga térmica)",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Vestimenta adequada, protetor solar",
    controls: "Pausas em ambiente climatizado, hidratação constante",
    legislation: "NR-15"
},
{
    id: "I-4",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana", 
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Exposição à Radiação Não Ionizante - Radiação Solar",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Protetor solar, óculos escuros, chapéu",
    controls: "Evitar exposição nos horários de pico",
    legislation: "NR-15"
},
{
    id: "I-5",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno", 
    risk: "Exposição à Radiação Não Ionizante- Operações de Soldagem",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Óculos de proteção com filtro UV",
    controls: "Área isolada, sinalização adequada",
    legislation: "NR-15"
},
{
    id: "I-6",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Inalação de poeira mineral (contendo sílica livre cristalizada)", 
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Sistema de exaustão, umidificação do ambiente",
    legislation: "NR-15"
},
{
    id: "I-7",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Inalação de poeira metálica",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Máscara PFF1",
    controls: "Ventilação local exaustora",
    legislation: "NR-15"
},
{
    id: "I-8",
    area: "Manutenção Mecânica", 
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Inalação de gases ácidos",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Máscara com filtro químico",
    controls: "Monitoramento atmosférico, ventilação",
    legislation: "NR-15"
},
{
    id: "I-9",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno", 
    risk: "Inalação de fumos metálicos",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Máscara PFF2",
    controls: "Ventilação local exaustora",
    legislation: "NR-15"
},
{
    id: "I-10",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Postura de pé por longos períodos",
    frequency: 4,
    severity: 2, 
    score: 8,
    riskLevel: "Baixo",
    ppe: "Calçado de segurança com palmilha antifatiga",
    controls: "Pausas ativas, rodízio de atividades",
    legislation: "NR-17"
},
{
    id: "I-11",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno", 
    risk: "Postura restrita de longa duração",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Nenhum específico",
    controls: "Ginástica laboral, pausas programadas",
    legislation: "NR-17"
},
{
    id: "I-12",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Ataque de ser vivo com peçonha", 
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Botas de segurança, luvas de couro",
    controls: "Manutenção da área limpa, inspeção prévia",
    legislation: "NR-31"
},
{
    id: "I-13",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Contato com Energia elétrica",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Luvas de borracha, botas isolantes",
    controls: "Bloqueio e etiquetagem, treinamento específico",
    legislation: "NR-10"
},
{
    id: "I-14",
    area: "Manutenção Mecânica", 
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Contato com Material/Produto Inflamável/Combustível (serviços de soldagem e corte)",
    frequency: 4,
    severity: 3,
    score: 12,
    riskLevel: "Médio",
    ppe: "Luva de raspa, óculos de proteção, avental",
    controls: "Área isolada, extintores disponíveis, treinamento específico",
    legislation: "NR-23"
},
{
    id: "I-15",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno", 
    risk: "Contato com Objeto/ material cortante",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Luvas de malha de aço",
    controls: "Organização do local, treinamento",
    legislation: "NR-12"
},
{
    id: "I-16",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno",
    risk: "Impacto por Objeto Projetado",
    frequency: 4,
    severity: 2, 
    score: 8,
    riskLevel: "Baixo",
    ppe: "Óculos de proteção, capacete",
    controls: "Sinalização de área, barreiras de proteção",
    legislation: "NR-18"
},
{
    id: "I-17",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Aplic. Grafite Alianças Forno", 
    risk: "Queda de pessoa com diferença de nível - Trabalho em altura",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Cinto de segurança tipo paraquedista, capacete",
    controls: "Plataforma de trabalho, treinamento NR-35",
    legislation: "NR-35"
},
{
    id: "I-18",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Exposição à Ruído contínuo",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Protetor auricular",
    controls: "Manutenção preventiva de equipamentos",
    legislation: "NR-15"
},
{
    id: "I-19",
    area: "Manutenção Mecânica", 
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Exposição à Vibração de Corpo Inteiro (VCI)",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Calçado de segurança com amortecimento",
    controls: "Limitação do tempo de exposição",
    legislation: "NR-15"
},
{
    id: "I-20",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest", 
    risk: "Exposição à Calor (Sobrecarga térmica)",
    frequency: 3,
    severity: 2,
    score: 6,
    riskLevel: "Baixo",
    ppe: "Vestimenta adequada",
    controls: "Pausas em ambiente climatizado",
    legislation: "NR-15"
},
{
    id: "I-21",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Exposição à Radiação Não Ionizante - Radiação Solar",
    frequency: 3,
    severity: 1, 
    score: 3,
    riskLevel: "Baixo",
    ppe: "Protetor solar",
    controls: "Evitar exposição nos horários de pico",
    legislation: "NR-15"
},
{
    id: "I-22",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest", 
    risk: "Exposição à Radiação Não Ionizante- Operações de Soldagem",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Óculos de proteção com filtro UV",
    controls: "Área isolada",
    legislation: "NR-15"
},
{
    id: "I-23",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Inalação de poeira mineral (contendo sílica livre cristalizada)",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Máscara PFF2",
    controls: "Ventilação local exaustora",
    legislation: "NR-15"
},
{
    id: "I-24",
    area: "Manutenção Mecânica", 
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Inalação de poeira metálica",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Máscara PFF1",
    controls: "Ventilação local exaustora",
    legislation: "NR-15"
},
{
    id: "I-25",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest", 
    risk: "Inalação de gases ácidos",
    frequency: 3,
    severity: 4,
    score: 12,
    riskLevel: "Médio",
    ppe: "Máscara com filtro químico",
    controls: "Monitoramento atmosférico, ventilação forçada",
    legislation: "NR-15"
},
{
    id: "I-26",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Inalação de fumos metálicos",
    frequency: 3,
    severity: 4, 
    score: 12,
    riskLevel: "Médio",
    ppe: "Máscara PFF2",
    controls: "Ventilação local exaustora, monitoramento",
    legislation: "NR-15"
},
{
    id: "I-27",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest", 
    risk: "Postura de pé por longos períodos",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Calçado de segurança com palmilha antifatiga",
    controls: "Pausas ativas",
    legislation: "NR-17"
},
{
    id: "I-28",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Postura restrita de longa duração",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Nenhum específico",
    controls: "Ginástica laboral",
    legislation: "NR-17"
},
{
    id: "I-29",
    area: "Manutenção Mecânica", 
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Ataque de ser vivo com peçonha",
    frequency: 3,
    severity: 3,
    score: 9,
    riskLevel: "Baixo",
    ppe: "Botas de segurança",
    controls: "Manutenção da área limpa",
    legislation: "NR-31"
},
{
    id: "I-30",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest", 
    risk: "Contato com Energia elétrica",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Luvas de borracha",
    controls: "Bloqueio e etiquetagem",
    legislation: "NR-10"
},
{
    id: "I-31",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Contato com Material/Produto Inflamável/Combustível (serviços de soldagem e corte)",
    frequency: 3,
    severity: 4, 
    score: 12,
    riskLevel: "Médio",
    ppe: "Luva de raspa, óculos de proteção",
    controls: "Área isolada, extintores disponíveis",
    legislation: "NR-23"
},
{
    id: "I-32",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest", 
    risk: "Contato com Objeto/ material cortante",
    frequency: 3,
    severity: 2,
    score: 6,
    riskLevel: "Baixo",
    ppe: "Luvas de malha de aço",
    controls: "Organização do local",
    legislation: "NR-12"
},
{
    id: "I-33",
    area: "Manutenção Mecânica",
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Impacto por Objeto Projetado",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Óculos de proteção",
    controls: "Sinalização de área",
    legislation: "NR-18"
},
{
    id: "I-34",
    area: "Manutenção Mecânica", 
    location: "ADM",
    activity: "CQ - Verificação Eq Laboratório - Semest",
    risk: "Queda de pessoa com diferença de nível - Trabalho em altura",
    frequency: 3,
    severity: 1,
    score: 3,
    riskLevel: "Baixo",
    ppe: "Cinto de segurança",
    controls: "Plataforma de trabalho",
    legislation: "NR-35"
},
{
    id: "I-35",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral", 
    risk: "Exposição à Ruído contínuo",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Protetor auricular",
    controls: "Manutenção preventiva de equipamentos, rodízio de funcionários",
    legislation: "NR-15"
},
{
    id: "I-36",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Exposição à Vibração de Corpo Inteiro (VCI)",
    frequency: 4,
    severity: 2, 
    score: 8,
    riskLevel: "Baixo",
    ppe: "Calçado de segurança com amortecimento",
    controls: "Limitação do tempo de exposição, pausas programadas",
    legislation: "NR-15"
},
{
    id: "I-37",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral", 
    risk: "Exposição à Calor (Sobrecarga térmica)",
    frequency: 4,
    severity: 4,
    score: 16,
    riskLevel: "Médio",
    ppe: "Vestimenta adequada, protetor solar",
    controls: "Pausas em ambiente climatizado, hidratação constante, monitoramento térmico",
    legislation: "NR-15"
},
{
    id: "I-38",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Exposição à Radiação Não Ionizante - Radiação Solar",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Protetor solar, óculos escuros",
    controls: "Evitar exposição nos horários de pico",
    legislation: "NR-15"
},
{
    id: "I-39",
    area: "Manutenção Mecânica", 
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Exposição à Radiação Não Ionizante- Operações de Soldagem",
    frequency: 4,
    severity: 2,
    score: 8,
    riskLevel: "Baixo",
    ppe: "Óculos de proteção com filtro UV",
    controls: "Área isolada, sinalização adequada",
    legislation: "NR-15"
},
{
    id: "I-40",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral", 
    risk: "Inalação de poeira mineral (contendo sílica livre cristalizada)",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Sistema de exaustão, umidificação do ambiente",
    legislation: "NR-15"
},
{
    id: "I-41",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Inalação de poeira metálica",
    frequency: 4,
    severity: 1, 
    score: 4,
    riskLevel: "Baixo",
    ppe: "Máscara PFF1",
    controls: "Ventilação local exaustora",
    legislation: "NR-15"
},
{
    id: "I-42",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral", 
    risk: "Inalação de gases ácidos",
    frequency: 4,
    severity: 3,
    score: 12,
    riskLevel: "Médio",
    ppe: "Máscara com filtro químico",
    controls: "Monitoramento atmosférico, ventilação forçada",
    legislation: "NR-15"
},
{
    id: "I-43",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Inalação de fumos metálicos",
    frequency: 4,
    severity: 3,
    score: 12,
    riskLevel: "Médio",
    ppe: "Máscara PFF2",
    controls: "Ventilação local exaustora, monitoramento",
    legislation: "NR-15"
},
{
    id: "I-44",
    area: "Manutenção Mecânica", 
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Postura de pé por longos períodos",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Calçado de segurança com palmilha antifatiga",
    controls: "Pausas ativas, rodízio de atividades",
    legislation: "NR-17"
},
{
    id: "I-45",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral", 
    risk: "Postura restrita de longa duração",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Nenhum específico",
    controls: "Ginástica laboral, pausas programadas",
    legislation: "NR-17"
},
{
    id: "I-46",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Ataque de ser vivo com peçonha",
    frequency: 4,
    severity: 2, 
    score: 8,
    riskLevel: "Baixo",
    ppe: "Botas de segurança, luvas de couro",
    controls: "Manutenção da área limpa, inspeção prévia",
    legislation: "NR-31"
},
{
    id: "I-47",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral", 
    risk: "Contato com Energia elétrica",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Luvas de borracha, botas isolantes",
    controls: "Bloqueio e etiquetagem, treinamento específico",
    legislation: "NR-10"
},
{
    id: "I-48",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Contato com Material/Produto Inflamável/Combustível (serviços de soldagem e corte)",
    frequency: 4,
    severity: 3,
    score: 12,
    riskLevel: "Médio",
    ppe: "Luva de raspa, óculos de proteção, avental",
    controls: "Área isolada, extintores disponíveis, treinamento específico",
    legislation: "NR-23"
},
{
    id: "I-49",
    area: "Manutenção Mecânica", 
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Contato com Objeto/ material cortante",
    frequency: 4,
    severity: 1,
    score: 4,
    riskLevel: "Baixo",
    ppe: "Luvas de malha de aço",
    controls: "Organização do local, treinamento",
    legislation: "NR-12"
},
{
    id: "I-50",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral", 
    risk: "Impacto por Objeto Projetado",
    frequency: 4,
    severity: 4,
    score: 16,
    riskLevel: "Médio",
    ppe: "Óculos de proteção, capacete, protetor facial",
    controls: "Sinalização de área, barreiras de proteção, isolamento da área",
    legislation: "NR-18"
},
{
    id: "I-51",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Insp Sist Inj Óleo W1V41 -Trimestral",
    risk: "Queda de pessoa com diferença de nível - Trabalho em altura",
    frequency: 4,
    severity: 2, 
    score: 8,
    riskLevel: "Baixo",
    ppe: "Cinto de segurança tipo paraquedista, capacete",
    controls: "Plataforma de trabalho, treinamento NR-35",
    legislation: "NR-35"
}
// ... continuaria com os demais 223 registros
];